site_name: agents-monitor-bills Documentation
site_description: Documentation for agents-monitor-bills
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
  features:
  - navigation.expand
nav:
- Home: index.md
- API Reference:
  - Developer: api/DEVELOPER.md
  - Readme: api/README.md
plugins:
- search
markdown_extensions:
- toc
- codehilite
- admonition
